services:
  config-frontend:
    container_name: uconfigit-frontend
    build:
      context: ./uconfigit-frontend
    ports:
      - "80:80"
    networks:
      - uconfigit-net

  config-backend:
    container_name: uconfigit-backend
    build:
      context: ./uconfigit-backend
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .env:/app/external.env
    networks:
      - uconfigit-net
  web:
    container_name: udoit-web
    image: ghcr.io/ucfopen/udoit:new-main-page-UX
    env_file:
      - .env

networks:
  uconfigit-net:
    driver: bridge
