services:
  config-frontend:
    container_name: uconfigit-frontend
    build:
      context: ./uconfigit-frontend
    ports:
      - "80:80"
    networks:
      - uconfigit-net

  config-backend:
    container_name: uconfigit-backend
    build:
      context: ./uconfigit-backend
    ports:
      - "5000:5000"
    volumes:
      - .env:/app/external.env
    networks:
      - uconfigit-net

networks:
  uconfigit-net:
    driver: bridge
